### PR TITLE
Added container env support for http/https proxy and socksProxy

### PR DESCRIPTION
**Pull request by erdnussflips**
Adds support for http/https and sockes proxy so that they can be defined with containers environment variables.

### CODE REVIEW

**Comment by pierre-guillot-sonarsource** [comment]
Hello, thanks for your PR. Do you know a way we could use to test this easily and make sure it works well ?

**Comment by erdnussflips** [comment]
@pierre-guillot-sonarsource do you mean an automatic test for the `run-tests.sh` or for manually testing (verifying) ?

**Comment by pierre-guillot-sonarsource** [comment]
@erdnussflips Automated would be perfect, but if you only have a manual way to test i'will take it :)

**Comment by erdnussflips** [comment]
@philippe-perrin-sonarsource how are the sonar or ldap variables that are also evaluated in the script tested?

**Comment by philippe-perrin-sonarsource** [comment]
> @philippe-perrin-sonarsource how are the sonar or ldap variables that are also evaluated in the script tested?
> 
> EDIT: You can check if the variables are evaluated, when you look at your SonarQuabe instance for the http variables under `Administration -> System -> Web -> Web JVM Properties`

@pierre-guillot-sonarsource

**Comment by erdnussflips** [comment]
@philippe-perrin-sonarsource sorry :D and thanks 👍

**Comment by pierre-guillot-sonarsource** [comment]
Thanks for your PR. This has been added to the product backlog : https://jira.sonarsource.com/browse/SONAR-12466

**Pull request closed without merging**
