### PR TITLE
Linting, GPG signature verification, and Docker secrets

### LINKED ISSUE #156: Support for docker secrets
Not sure if this is already supported, but I would love to have support for docker secrets in Sonarqube. Having to specify the database user/password directly in my compose file, prevents me from using versioning software.

### LINKED ISSUE #349: use `--no-install-recommends` with `apt-get install`
This option disables installation of recommended dependencies of the installed packages.

Canonical itself recommends using it (see https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends).

However, given the package we currently do install (`curl` `unzip` `libfreetype6` and `libfontconfig1`), the benefit are not obvious.

However, it's worth trying and confirming.

### LINKED ISSUE #363: Sonarqube Beta no longer validating downloaded artifacts on build
It appears that in the rewrite of the Sonarqube Dockerfiles, the beta images no longer perform any form of validation of the artifacts being downloaded and placed into the Docker image - the only security remaining is that of the use of TLS for the HTTP connection wherein the Sonarqube zip file is downloaded.  

While there is a code path which may provide implicit trust in the event that the image is built with the zip itself locally, the other branch wherein the zip is downloaded is used as a silent failover should the zip not be correctly loaded into the image by the Dockerfile.

A correct fix would be reimplementing GPG verification of any downloaded artifacts.  Yes, GPG is a pain to deal with, but it's far better than the consequences of a successful supply chain attack.  [The docker-library org has some guidance on effective use of fault-tolerant GPG verification here.](https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification)

### PR DESCRIPTION
**Pull request by konstruktoid**
Basic linting of the Dockerfiles,
Adds GPG signature verification (closes #363),
Uses `--no-install-recommends` (closes #349),
Adds skeleton support for Docker secrets (closes #156)

```
$ docker images sonarqube
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sonarqube           local-latest        c5e326b32f3f        18 minutes ago      570MB
sonarqube           developer-beta      cff979697db0        9 days ago          681MB
sonarqube           community-beta      9f896e5a7de4        9 days ago          575MB
sonarqube           latest              0956756d5b96        9 days ago          483MB
```

```
printf "sonarqube" | docker secret create sonarqube_jdbc_password -
docker service create --name sonarqube --secret sonarqube_jdbc_password -p 9000:9000 sonarqube
```

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by konstruktoid** [comment]
Travis fails, but I can't really fix the private repo errors.

```
The command "SQ_VERSION="$SONARQUBE_BUILD_NUMBER" ZIP_SERVER="repox.jfrog.io" ZIP_URL="https://repox.jfrog.io/repox/sonarsource/com/sonarsource/sonarqube/sonarqube-enterprise/$SONARQUBE_BUILD_NUMBER/sonarqube-enterprise-$SONARQUBE_BUILD_NUMBER.zip" ZIP_USERNAME="$ARTIFACTORY_PRIVATE_USERNAME" ZIP_PASSWORD="$ARTIFACTORY_PRIVATE_PASSWORD" ./8/build-docker-from-private-repo.sh enterprise --tag sonarqube:8-ee" exited with 1.

50.75s$ ./run-tests.sh "sonarqube:8-ee"

Unable to find image 'sonarqube:8-ee' locally

docker: Error response from daemon: manifest for sonarqube:8-ee not found.

See 'docker run --help'.
```

**Comment by konstruktoid** [comment]
How this PR is related to https://jira.sonarsource.com/browse/MMF-1931, @pierre-guillot-sonarsource (#41 (comment)):

_"Use the smallest base image as possible"_. Sorry to say this is a quite large one, but Java is Java. https://github.com/SonarSource/docker-sonarqube/blob/b84f9f27c0a52d850ec038f5b1ab772bd46e50e4/8/community/Dockerfile#L1

_"Do not package non-required tools inside the Docker image"_. Unused applications are removed after usage.
https://github.com/SonarSource/docker-sonarqube/blob/b84f9f27c0a52d850ec038f5b1ab772bd46e50e4/8/community/Dockerfile#L66-L68

_"Apply security best-practices"_. `ADD` is not used in the image.

_"Download packages securely using GPG and certificates"_. Files downloaded with `curl` and verified.
https://github.com/SonarSource/docker-sonarqube/blob/b84f9f27c0a52d850ec038f5b1ab772bd46e50e4/8/community/Dockerfile#L35-L38

_"consider adding the support for Docker/Kubernetes secrets"_. Basic secrets support has been added.
https://github.com/SonarSource/docker-sonarqube/blob/b84f9f27c0a52d850ec038f5b1ab772bd46e50e4/8/community/run.sh#L40-L45

**Comment by pierre-guillot-sonarsource** [comment]
ping @michal-duda-sonarsource @simonbrandhof

**Comment by konstruktoid** [comment]
Closing due to https://github.com/SonarSource/docker-sonarqube/pull/379#issuecomment-604570311 and https://github.com/SonarSource/docker-sonarqube/blob/master/README.md#contributing.

**Pull request closed without merging**
