### PR TITLE
Let the user set JVM and launch parameters

### PR DESCRIPTION
**Pull request by glanzi**
I am running SonarQube behind a reverse proxy and thus that i need a simple solution to set the system property to change the web context:
docker run --name sonarqube -p 9000:9000 --env JAVA_OPTS=-Dsonar.web.context=/sonarqube sonarqube:5.1

### CODE REVIEW

**Comment by dgageot** [comment]
Did you try passing the additional parameters to the docker command line? It's supposed to work. Please tell me if it doesn't.

```
docker run --name sonarqube -p 9000:9000 sonarqube:5.1 -Dsonar.web.context=/sonarqube
```

**Comment by glanzi** [comment]
Thanks for your answer. It works when i set the java environment property in the docker command parameter or in my case in docker-compose.yml like "command: -Dsonar.web.context=/sonar".

**Comment by dgageot** [comment]
good to hear! :-)

**Comment by Batmat** [comment]
Hi,
I know it's not really a question related to SonarQube, but I'm interesting in using that trick to pass parameters to Sonar, but using Docker Compose.

Compose lets you pass env variables in a std way, but can't find anything else to do what's above other than overriding the "command" with the additional params. 
We don't really like it because we have to copy/paste the existing CMD in the Dockerfile. So that's more a workaround than a solution in our opinion.

Do you know of a better way to do that with Compose ?

Thanks a lot.

**Comment by dgageot** [comment]
@Batmat sorry but no.

**Pull request closed without merging**
