### PR TITLE
[NO-JIRA] Remove unnecessary properties setup

### PR DESCRIPTION
**Pull request by carminevassallo**
We set several properties which are not mandatory. This PR has the goal of cleaning them up.

### CODE REVIEW

**Review by jCOTINEAU — APPROVED** [review]
lgtm.
We need to remember to change the docker-compose example related to the dce to add that path inside of it and in the documentation.

**Review by jacek-poreda-sonarsource — APPROVED** [review]
LGTM 👍

**Comment by carminevassallo** [comment]
I think @jCOTINEAU has a very good point. I'll update the examples in the context of this PR already.

**Comment by carminevassallo** [comment]
Given that the app nodes are identical replicas part of a Deployment, at the moment we can't avoid the cluttered-logs issue in these nodes. The problem is not affecting search nodes instead.

Therefore, we are gonna remove the cluttered-logs patch in the search nodes, but not in the app nodes. This would instead require some changes within the application.

**Review by jCOTINEAU — APPROVED** [review]
lgtm !

**Pull request merged**
