### PR TITLE
ADD: upgrade to sonarqube 7.3 and 7.4

### PR DESCRIPTION
**Pull request by pcollaog**
Add new sonarqube 7.3

### CODE REVIEW

**Comment by pcollaog** [comment]
Now is working and I installed on my docker swarm (update from 7.1 with /setup procedure)... works like a charm

**Comment by pcollaog** [comment]
Now I add support for sonarqube 7.4 ;)

**Comment by marcomsousa** [comment]
I build and upload Sonarqube 7.4 (unofficial) to docker hub.

docker pull marcomsousa/sonarqube
docker run marcomsousa/sonarqube

**Comment by DevKyleS** [comment]
@Godin Who needs to review?

**Comment by janos-ss** [comment]
Thank you for this contribution. I have added `7.4-community`,`7.4-community-alpine`, `6.7.6-community` and `6.7.6-community-alpine` in `master`, with some other improvements, so I'm closing this PR now. 

Btw, the updated images should become official when the maintainers of Docker Hub accept my PRs. Note that the `-alpine` images won't be official, because unfortunately they don't seem to work on Linux. See more info in [`develop.md`](https://github.com/SonarSource/docker-sonarqube/blob/master/develop.md)

**Pull request closed without merging**
