### PR TITLE
Release SonarQube 7.5 Developer Edition

### PR DESCRIPTION
**Pull request by Yopii**
Added `Developer Edition` image #223.

Migration is simple from the docker-compose template, just replace  : 
`image: sonarqube`
by 
`image: sonarqube:7.5-developer`

I tested a community installation and then migrated to `develop` and rollback to `community`. The versions work perfectly.

When using the `Developer Edition`, it is necessary to enter the license number. The server ID is kept, I didn't find any bugs on my side.

- [x] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [x] If the PR modifies or adds images, please use the `run-tests.sh imagedir` command to verify the image works
- [x] If the PR modifies or adds images, please try to make sure the images run correctly on Linux

### CODE REVIEW

**Comment by Mitsufumi** [comment]
I'm just about to look for the developer edition image.
And I run the container based on the image created on Yopii's edited Dockerfile.
@Yopii Thank you so much!!
screenshot

**Comment by martinmani** [comment]
> sonarqube:7.5-developer

is this image ( or 7.6-developer) pushed to docker hub?

**Comment by 123dev** [comment]
> 
> 
> > sonarqube:7.5-developer
> 
> is this image ( or 7.6-developer) pushed to docker hub?

I don't think neither is pushed, at least I couldn't find them, I had to build the image from the Dockerfile provided.

**Comment by claasd** [comment]
What is blocking this PR?

**Comment by DuAell** [comment]
Can you update this image to 7.7 please ?

**Comment by pierre-guillot-sonarsource** [comment]
Hi, thanks for your PR. We are planning to release officials images of DE and EE during https://jira.sonarsource.com/browse/MMF-1604. we are fully aware that this is a community request. I'm closing this PR for now as we will release DE and EE on more recents versions of SQ.

**Comment by meedel** [comment]
what about an image for 7.9.1 LTS developer version!

**Comment by pierre-guillot-sonarsource** [comment]
We will release a 8.x version first. If everything is fine, maybe we will consider release a LTS version as well

**Pull request closed without merging**
