### PR TITLE
fix run docker

### PR DESCRIPTION
**Pull request by letnab**
Without this setting, launching the container is not possible.

Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes. 
Please ensure your pull request adheres to the following guidelines:
- [ ] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] If the PR modifies or adds images, use the `run-tests.sh imagedir` command to verify the image works
- [ ] If the PR modifies or adds images, try to make sure the images run correctly on Linux

### CODE REVIEW

**Comment by pierre-guillot-sonarsource** [comment]
Hey @tobias-trabelsi-sonarsource or @michal-duda-sonarsource , what do you think about this?

**Comment by letnab** [comment]
Hi @tobias-trabelsi-sonarsource 
After building the docker image, it did not start.
```
 docker run -P --rm docker.sberned.ru/sonarqube/sonarqube:8.3.1-community                                                                        
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bin/run.sh\": permission denied": unknown.
```

**Comment by letnab** [comment]
Hi @tobias-trabelsi-sonarsource 

Hi @tobias-trabelsi-sonarsource
After building the docker image, it did not start.

```
 docker run -P --rm docker.sqar.ru/sonarqube/sonarqube:8.3.1-community                                                                        
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bin/run.sh\": permission denied": unknown.
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @letnab 
i can not reproduce this, as the registry that you stated seems not to be public. maybe my test can help you:

```bash
cd docker-sonarqube/8/community
docker build -t testing/sonarqube:8.3.1-community .
docker run -p 9000:9000 -d testing/sonarqube:8.3.1-community
```

After that sonarqube is coming up just fine and is reachable on port 9000 (default port). When i have a look inside the container the changed you want to make with this PR are already present.

```bash
bash-5.0# ls -alh
total 76K    
drwxr-xr-x    1 sonarqub sonarqub    4.0K May  7 13:41 .
drwxr-xr-x    1 root     root        4.0K May 26 08:25 ..
-rw-r--r--    1 sonarqub sonarqub    7.5K May  7 13:22 COPYING
drwxr-xr-x    1 sonarqub sonarqub    4.0K May 26 08:25 bin
drwxr-xr-x    2 sonarqub sonarqub    4.0K May  7 13:22 conf
drwx------    1 sonarqub sonarqub    4.0K May 26 08:49 data
drwxr-xr-x    7 sonarqub sonarqub    4.0K May  7 13:22 elasticsearch
drwx------    1 sonarqub sonarqub    4.0K May 26 08:49 extensions
drwxr-xr-x    6 sonarqub sonarqub    4.0K May  7 13:41 lib
drwx------    1 sonarqub sonarqub    4.0K May 26 08:50 logs
drwx------    1 sonarqub sonarqub    4.0K May 26 08:50 temp
drwxr-xr-x    6 sonarqub sonarqub    4.0K May  7 13:41 web
```

**Comment by letnab** [comment]
It’s strange. Now I did the assembly again, everything was assembled and started without problems. Then PR can be removed

**Comment by tobias-trabelsi-sonarsource** [comment]
Good that it's working for you now (:

**Pull request closed without merging**
