### PR TITLE
Elasticsearch in SonarQube 6.6 requires non-root user and bash

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by jan-z** [comment]
Shouldn't the volume get chown'ed to the sonarqube user in the run script? To enable upgrade from older versions.

**Comment by Godin** [comment]
@jan-z `chown` added into run scripts

**Comment by jan-z** [comment]
@Godin thanks, works fine for me now. Upgrade is working as well. LGTM

**Comment by Godin** [comment]
@jan-z thank for reviewing and testing! :thumbsup:

**Pull request merged**
