### PR TITLE
feat(docker): Email env var

### LINKED ISSUE #416: Init Email configuration from env var
Would be nice to setup Email configuration from environment variables (like `email.* `):

From:
https://github.com/SonarSource/docker-sonarqube/blob/27217fb0cfcd9469571eff710eae434a92a26f72/8/enterprise/run.sh#L17-L27

To:
```java
if [[ "$envvar_key" =~ sonar.* ]] || [[ "$envvar_key" =~ ldap.* ]] || [[ "$envvar_key" =~ email.* ]]; then 
```

Thread: https://community.sonarsource.com/t/init-email-configuration-from-env-var-with-docker/27608

Will probably send a PR for that.

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Environment variables to configure email settings and to fix #416

Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>

### CODE REVIEW

**Comment by tobias-trabelsi-sonarsource** [comment]
Hey @madmath03 ,
thanks for your contribution. i will have a closer look at your PR soon but i discovered something else while having a short look that i need to clarify first.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @madmath03 ,
i have discussed this within the team and i will have to mark your PR as on hold for now. 

while the changes that you want to have are present with the changes from this PR there is the [plan to redesign the way that these settings are set](https://jira.sonarsource.com/browse/SONAR-11818), so the key prefix (email.) is very likely to be changed in the near future. we don''t want to enable a feature that is then used in the wild knowing we will have a breaking change soon.

i hope you understand and when we are working on [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818) we will come back to you with the appropriate key prefix

**Comment by pierre-guillot-sonarsource** [comment]
Hey @tobias-trabelsi-sonarsource, if this is going to be addressed with SONAR-11818, maybe we could update the Jira ticket and close this PR?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @madmath03 ,
after a discussion with @pierre-guillot-sonarsource we will close this PR as we will hopefully include a proper way to add this functionality with SONAR-11818. thank you again for the contribution and effort you put in this

**Pull request closed without merging**
