### PR TITLE
expose conf and logs directory as docker volume

### LINKED ISSUE #44: expose conf and logs directory as docker volume
exposing conf and logs directory as docker volume

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #44

### CODE REVIEW

**Comment by Godin** [comment]
@LorenzoBettini  first of all excuse me that it took so long to take a look on this - was on vacation and traveling.

Unfortunately detailed information is not provided along with your change as well as in #44. So based on your https://github.com/SonarSource/docker-sonarqube/issues/34#issuecomment-264516923 I tried to guess that this is about command such as:
```
docker run -v /tmp/sq/conf:/opt/sonarqube/conf sonarqube sh
```
and you expect that file `/tmp/sq/conf/sonar.properties` will be created, but this is not the case even after this change - quoting https://docs.docker.com/engine/tutorials/dockervolumes/ :
> Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization. (**Note that this does not apply when mounting a host directory.**)

So could you please elaborate more about rationale for this change?

**Comment by LorenzoBettini** [comment]
@Godin of course my comment https://github.com/SonarSource/docker-sonarqube/issues/34#issuecomment-264516923 is completely wrong, as you said, and I forgot to update it.  This Pr is just for #44 which I seem to understand would still be useful, so that conf and logs are persisted in volumes that can be later inspected or modified. So it has nothing to do with mounted host directories.

**Comment by Godin** [comment]
@LorenzoBettini thank you for your contribution! :thumbsup:

**Comment by Godin** [comment]
@LorenzoBettini after merge of this PR came across https://github.com/SonarSource/docker-sonarqube/issues/16#issuecomment-256426270 Probably I lack knowledge of Docker best practices to understand all this mess around volumes, so could you please participate in mentioned thread? Thanks in advance.

**Comment by Godin** [comment]
Reverted in https://github.com/SonarSource/docker-sonarqube/commit/80366e3419d698b4bba4447f153418ef64b3b705

**Pull request merged**
