### PR TITLE
SonarQube 5.6.7

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by Godin** [comment]
This also requires merge of https://github.com/docker-library/official-images/pull/3496

**Comment by tianon** [comment]
This needed to update `SONAR_VERSION` as well, right?

**Comment by Godin** [comment]
@tianon ouch, you're right, I was too fast

**Comment by Godin** [comment]
@tianon fixed in 65090c41e5e8157e656e6a7fd3853f5e09f6eae6

**Pull request merged**
