### PR TITLE
SONAR-13182 switch to alpine

### PR DESCRIPTION
**Pull request by michal-duda-sonarsource**
- switch base image to alpine
- allow running the image as an arbitrary user
- support running the image in read-only mode (when using volumes)

### CODE REVIEW

**Comment by simonbrandhof** [comment]
The commit should reference SONAR-13156 first. And could the changes related to SONAR-13182  be split into dedicated commits, or at least listed?

**Comment by konstruktoid** [comment]
@michal-duda-sonarsource @pierre-guillot-sonarsource 
so I don't get the logic here, you got #368 from February that closes a bunch of issues and uses Alpine as base with no comments at all and then you open a PR that creates even more conflicts, and even goes against https://github.com/SonarSource/sonar-scanner-cli-docker/pull/36#issuecomment-601320716 regarding using Alpine.

Is there a point with these public repositories?
ref https://github.com/SonarSource/sonar-scanner-cli-docker/issues/41

**Comment by michal-duda-sonarsource** [comment]
@konstruktoid the issue here is every new feature has to be internally discussed and validated before being merged for which we didn't have time when you opened the PR, everyone was busy working on non-Docker stuff. Your PR addresses too many issues at once and breaks backwards compatibility with previous image which might interfere with existing workflows. Internally people are opposed to supporting Docker Secrets too.

As for Alpine- I don't think there is conflict with what I've said in SonarSource/sonar-scanner-cli-docker#36. We wanted to evaluate other base images (and we did) but in the end we settled on Alpine (at least for now) for SonarQube. It might be different for `scanner-cli` since we probably have more options there (like the Distroless image, which we couldn't use here).

I know it's after the fact but for what it's worth we updated the README to clarify our approach to contributions (and raising issues/asking questions).

**Comment by petemounce** [comment]
> @konstruktoid the issue here is every new feature has to be internally discussed and validated before being merged for which we didn't have time when you opened the PR, everyone was busy working on non-Docker stuff. Your PR addresses too many issues at once and breaks backwards compatibility with previous image which might interfere with existing workflows. Internally people are opposed to supporting Docker Secrets too.
> 
> As for Alpine- I don't think there is conflict with what I've said in [SonarSource/sonar-scanner-cli-docker#36](https://github.com/SonarSource/sonar-scanner-cli-docker/pull/36). We wanted to evaluate other base images (and we did) but in the end we settled on Alpine (at least for now) for SonarQube. It might be different for `scanner-cli` since we probably have more options there (like the Distroless image, which we couldn't use here).
> 
> I know it's after the fact but for what it's worth we updated the README to clarify our approach to contributions (and raising issues/asking questions).

@michal-duda-sonarsource would you mind creating a `CONTRIBUTING.md` that sets those expectations? github will then auto-link that inside of the UI when a PR is opened. https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by michal-duda-sonarsource** [comment]
@petemounce good idea 👍. Done.

**Pull request merged**
