### PR TITLE
Updated Docker Compose configuration to version 2.

### PR DESCRIPTION
**Pull request by andreas-lundgren-storytel**
Also:
* Fixed issue with database data not being persisted for some versions of Docker due to explicis VOLUME mapping, see comment in source code.
* Added recipe for Salt Slack Docker Container Configuration Management.

### CODE REVIEW

**Comment by Godin** [comment]
@andreas-lundgren-storytel addition of a recipe for "Salt Slack Docker Container Configuration Management" implies that it will need maintenance here in future and there are some doubts about this. IMO will be better to stick to a standard docker toolbox, which includes just docker-compose. So could you please update PR and leave only changes for docker-compose?

**Comment by andreas-lundgren-storytel** [comment]
Sure!
(Sorry, I'm not used to work with PR on forks. I think I manages to close the PR...)

**Comment by Godin** [comment]
@andreas-lundgren-storytel no pb and thank you for your understanding

**Comment by Godin** [comment]
Superseded by #33

**Pull request closed without merging**
